language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t luizparo/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true luizparo/react-test npm test

after_success:
    - docker build -t luizparo/multi-client ./client
    - docker build -t luizparo/multi-nginx ./nginx
    - docker build -t luizparo/multi-server ./server
    - docker build -t luizparo/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push luizparo/multi-client
    - docker push luizparo/multi-nginx
    - docker push luizparo/multi-server
    - docker push luizparo/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-1
    env: MultiDockerWithVpc-env
    bucket_name: elasticbeanstalk-us-east-1-123777059602
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY